sudo: required
services:
    - docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm test

after_success:
    - docker build -t knatschsack/multi-client ./client
    - docker build -t knatschsack/multi-nginx ./nginx
    - docker build -t knatschsack/multi-server ./server
    - docker build -t knatschsack/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push knatschsack/multi-client
    - docker push knatschsack/multi-nginx
    - docker push knatschsack/multi-server
    - docker push knatschsack/multi-worker
